### ISSUE TITLE
xcode15.3.0使用hanabi方案移植编译llvm16.0.0，开启字符串混淆后编译报错

### ISSUE THREAD

**Issue by anjiuzhe** [61bcdefg/Hikari-LLVM15-Core#3]
日志如下：
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               clang [67427]
Path:                  /Applications/Xcode-15.3.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
Identifier:            clang
Version:               ???
Code Type:             ARM-64 (Native)
Parent Process:        clang [67417]
Responsible:           Xcode [66843]
User ID:               501

Date/Time:             2024-05-13 16:08:21.1358 +0800
OS Version:            macOS 14.4.1 (23E224)
Report Version:        12
Anonymous UUID:        32461C17-E5B7-DD26-A305-9F096C3871B9

Sleep/Wake UUID:       4FDE575A-2AC5-4B85-A4BA-322620452FED

Time Awake Since Boot: 65000 seconds
Time Since Wake:       7603 seconds

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   clang [67427]

Application Specific Information:
abort() called

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x181866a60 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x18189ec20 pthread_kill + 288
2   libsystem_c.dylib             	       0x1817abab4 __abort + 136
3   libsystem_c.dylib             	       0x1817aba2c abort + 192
4   libsystem_malloc.dylib        	       0x1816bbaa8 malloc_vreport + 896
5   libsystem_malloc.dylib        	       0x1816bf114 malloc_report + 64
6   libsystem_malloc.dylib        	       0x1816d9494 find_zone_and_free + 528
7   libLLVMHanabiDeps.dylib       	       0x10e3f4ba0 llvm::detail::DenseMapPair<llvm::Type*, llvm::PointerType*>* llvm::DenseMapBase<llvm::DenseMap<llvm::Type*, llvm::PointerType*, llvm::DenseMapInfo<llvm::Type*, void>, llvm::detail::DenseMapPair<llvm::Type*, llvm::PointerType*>>, llvm::Type*, llvm::PointerType*, llvm::DenseMapInfo<llvm::Type*, void>, llvm::detail::DenseMapPair<llvm::Type*, llvm::PointerType*>>::InsertIntoBucket<llvm::Type*>(llvm::detail::DenseMapPair<llvm::Type*, llvm::PointerType*>*, llvm::Type*&&) + 148
8   libLLVMHanabiDeps.dylib       	       0x10e3f1fec llvm::PointerType::get(llvm::LLVMContext&, unsigned int) + 212
9   libLLVMHanabiDeps.dylib       	       0x10e362b08 llvm::GlobalVariable::GlobalVariable(llvm::Module&, llvm::Type*, bool, llvm::GlobalValue::LinkageTypes, llvm::Constant*, llvm::Twine const&, llvm::GlobalVariable*, llvm::GlobalValue::ThreadLocalMode, std::__1::optional<unsigned int>, bool) + 112
10  libLLVMHanabi.dylib           	       0x10c07ef70 llvm::StringEncryption::runOnModule(llvm::Module&) + 716
11  libLLVMHanabi.dylib           	       0x10c08cec8 llvm::Obfuscation::runOnModule(llvm::Module&) + 716
12  libLLVMHanabi.dylib           	       0x10c08ca44 llvm::ObfuscationPass::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) + 40
13  clang                         	       0x105746ffc llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) + 208
14  clang                         	       0x1060b4708 (anonymous namespace)::EmitAssemblyHelper::EmitAssembly(clang::BackendAction, std::__1::unique_ptr<llvm::raw_pwrite_stream, std::__1::default_delete<llvm::raw_pwrite_stream>>) + 3804
15  clang                         	       0x1060b2e60 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, std::__1::unique_ptr<llvm::raw_pwrite_stream, std::__1::default_delete<llvm::raw_pwrite_stream>>) + 328
16  clang                         	       0x10638c0ac clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) + 1244
17  clang                         	       0x1077c09d4 clang::ParseAST(clang::Sema&, bool, bool) + 356
18  clang                         	       0x10663ed24 clang::FrontendAction::Execute() + 60
19  clang                         	       0x1065b7008 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 248
20  clang                         	       0x1066a0a70 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 2996
21  clang                         	       0x1049b0aec cc1_main(llvm::ArrayRef<char const*>, char const*, void*) + 1696
22  clang                         	       0x1049a9af0 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) + 868
23  clang                         	       0x1049a95e0 driver_main(int, char**) + 3820
24  clang                         	       0x1049a8694 clang_main(int, char**) + 248
25  dyld                          	       0x1815160e0 start + 2360

**Comment by 61bcdefg** [comment]
[https://github.com/61bcdefg/Hikari-LLVM15/issues/94#issuecomment-1986699791](https://github.com/61bcdefg/Hikari-LLVM15/issues/94#issuecomment-1986699791)
