### ISSUE TITLE
Obfuscation似乎缺少了一些.h？

### ISSUE THREAD

**Issue by GoDaie** [61bcdefg/Hikari-LLVM15-Core#4]
在构建Hanabi的时候，到执行ninja LLVMHanabi 会提示缺少一些.h文件，例如Obfuscation.h。
![WX20240516-200314](https://github.com/61bcdefg/Hikari-LLVM15-Core/assets/15681616/0eaec80f-e682-47a4-bbc7-d66837fe2443)

clone LLVM 16.0.0，cd到../llvm-project执行git submodule update --init --recursive --remote

clone [Hanabi](https://github.com/61bcdefg/Hanabi.git)到../llvm-project/llvm/projects/
![截屏2024-05-16 20 16 17](https://github.com/61bcdefg/Hikari-LLVM15-Core/assets/15681616/e8164b49-06c6-436a-b8b2-8e468579ac48)

将此Obfuscation clone到../llvm-project/llvm/lib/Transforms/，然后在CMakeLists.txt中添加add_subdirectory(Obfuscation)
![截屏2024-05-16 20 16 49](https://github.com/61bcdefg/Hikari-LLVM15-Core/assets/15681616/30deb856-be13-44ca-8f3c-afee861dca67)

然后cd到../llvm-project/llvm/projects/ 执行cmake ../llvm-project/llvm -DCMAKE_BUILD_TYPE=Release -DLLVM_ABI_BREAKING_CHECKS=FORCE_OFF -G Ninja 顺利完成
![截屏2024-05-16 20 17 46](https://github.com/61bcdefg/Hikari-LLVM15-Core/assets/15681616/b77a1196-b8d3-4dcb-b33f-dcc2cf707540)

然后继续ninja LLVMHanabi 就会提示上面缺少Obfuscation.h。
![WX20240516-200314](https://github.com/61bcdefg/Hikari-LLVM15-Core/assets/15681616/0eaec80f-e682-47a4-bbc7-d66837fe2443)

请问是我在构建过程中遗漏了什么步骤吗？

**Comment by 61bcdefg** [comment]
你没有clone Headers
