### ISSUE TITLE
Bogus Control Flow Crash

### ISSUE THREAD

**Issue by InstinctTheDevil** [61bcdefg/Hikari-LLVM15-Core#8]
Hello,

I tried version 15 and 17 and both are crashing when using Bogus Control Flow.

Doing Post-Run Cleanup
Hikari Out
Spend Time: 1.3452160s
Assertion failed: unsigned(ObjectIdx + NumFixedObjects) < Objects.size() && "Invalid Object Idx!", file C:\Users\PC\Hikari-LLVM15\llvm\include\llvm/CodeGen/MachineFrameInfo.h, line 485

**Comment by 61bcdefg** [comment]
Same as https://github.com/61bcdefg/Hikari-LLVM15/issues/124
